name: Build docker

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: satackey/action-docker-layer-caching@v0.0.11
      continue-on-error: true
    - name: Get yt-dlp executable
      uses: dsaltares/fetch-gh-release-asset@1.0.0
      with:
        repo: bo0tzz/yt-dlp
        file: yt-dlp
    - name: Push to GitHub Container Registry
      uses: docker/build-push-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io
        repository: bo0tzz/yt-dlp
        tag_with_ref: true